---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install testing requirements
      ansible.builtin.package:
        name: socat
        state: present
      notify:
        - Uninstall testing requirements

    - name: Check if port responds
      ansible.builtin.wait_for:
        port: "{{ item }}"
      loop:
        - 80
        - 443
        - 8405

    - name: Check of content can be retrieved
      ansible.builtin.uri:
        url: "{{ item }}"
        validate_certs: false
        status_code:
          - 200
      loop:
        - "http://localhost/"
        - "https://localhost/"
        - "http://localhost:8405/"

    - name: Check if stats are available
      ansible.builtin.shell:
        cmd: "bash -o pipefail -c 'echo 'show stat' | socat unix-connect:/var/lib/haproxy/stats stdio'"
      changed_when: false

  handlers:
    - name: Uninstall testing requirements
      ansible.builtin.package:
        name: socat
        state: absent
